# Generated by Django 4.2.17 on 2025-01-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorgeneral',
            name='laboratorio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director_general', to='laboratorio.laboratorio'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='laboratorio.laboratorio'),
        ),
    ]
