# Generated by Django 4.2.17 on 2025-01-14 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_alter_directorgeneral_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'verbose_name': 'Laboratorio', 'verbose_name_plural': 'Laboratorios'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
